services:
  db:
    image: postgres:16
    container_name: family-album-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=fa_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fa_db
    ports:
      - "5432:5432"
    volumes:
      - family_album_db_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
  web:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules # bind mountによる上書きから除外
      - /app/api/node_modules # bind mountによる上書きから除外

volumes:
  family_album_db_data:
